apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: final-project-tasks
spec:
  workspaces:
    - name: source
  steps:
    - name: cleanup
      image: alpine:latest
      script: |
        echo "Cleaning up workspace..."
        rm -rf $(workspaces.source.path)/*

    - name: git-clone
      image: alpine/git:latest
      script: echo "Cloning project to cluster workspace"

    - name: flake8/eslint
      image: python:3.11-slim
      script: echo "Running lint check validation"

    - name: nose/jest
      image: python:3.11-slim
      workingDir: $(workspaces.source.path)
      script: |
        pip install -r requirements.txt
        python -m unittest discover -s service

    - name: buildah
      image: alpine:latest
      script: echo "Building final container image"

    - name: deploy/openshift-client (deploy)
      image: alpine:latest
      script: echo "Deploying target application to open ports"